# Site settings
title: "Tamás Losonczi's personal site"
description: "Personal site for sharing knowledge."
title_description: "I’m a programmer from Budapest. See my projects <a href=\"../projects\">here</a>."
title_image: "./images/avatar.jpg"
# google_analytics: "UA-20365477-4"
disqus_account: tamslosonczi
post_limit: 5

# Social usernames/URLs
github_username: LosoncziTamas
medium_link: https://medium.com/@losonczi.tamas91
linkedin_link: https://www.linkedin.com/in/tam%C3%A1s-losonczi-77b13699/

# Footer
# footer_left: "Made with <i class=\"fa fa-heart\"></i> by"
# footer_right: "&lt;/&gt; on Github &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

# Plugins
gems:
  - jekyll-seo-tag